### PR TITLE
Vehicle exception

### PR DESCRIPTION
**Pull request by AnishBplayz**
Added a check to not throw weapon if ped is in a vehicle

### CODE REVIEW

**Comment by iSentrie** [comment]
```lua
if cache.vehicle then return end
```

**Comment by AnishBplayz** [comment]
> ```lua
> if cache.vehicle then return end
> ```
Is this using the ox_lib ? i am not familiar with it yet.

**Comment by PickleModifications** [comment]
This is a feature, not a bug.

**Comment by PickleModifications** [comment]
Throwing from vehicles is a feature of this script.

**Comment by AnishBplayz** [comment]
Ohh, okay didn't know about it

**Pull request closed without merging**
